dist: trusty
sudo: required
language: go
go:
- master
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
- sudo apt-get update -q
- sudo apt-get --no-install-recommends install texlive texlive-lang-german texlive-science
  texlive-latex-extra texlive-bibtex-extra biber texlive-generic-extra -y
install:
  - go get github.com/spf13/hugo
script:
- make clean
- make build
- make homepage
deploy:
  local_dir: docs/public # Default static site output dir for Hugo
  repo: wysiib/ai_script # This is the slug of the repo you want to deploy your site to
  target_branch: gh-pages # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: sebastian@krin.gs
  name: "Sebastian Krings"
  on:
    branch: master